### ISSUE TITLE
error during install

### ISSUE THREAD

**Issue by peekaa** [languitar/autosuspend#2] opened 2016-03-24 18:14 UTC
1. I just got error during install:

        root@linuxbox:~/autosuspend# python3 setup.py install
        running install
        Checking .pth file support in /usr/local/lib/python3.4/dist-packages/
        /usr/bin/python3 -E -c pass
        TEST PASSED: /usr/local/lib/python3.4/dist-packages/ appears to support .pth files
        running bdist_egg
        running egg_info
        creating autosuspend.egg-info
        writing dependency_links to autosuspend.egg-info/dependency_links.txt
        writing autosuspend.egg-info/PKG-INFO
        writing requirements to autosuspend.egg-info/requires.txt
        writing top-level names to autosuspend.egg-info/top_level.txt
        writing manifest file 'autosuspend.egg-info/SOURCES.txt'
        reading manifest file 'autosuspend.egg-info/SOURCES.txt'
        writing manifest file 'autosuspend.egg-info/SOURCES.txt'
        installing library code to build/bdist.linux-x86_64/egg
        running install_lib
        warning: install_lib: 'build/lib' does not exist -- no Python modules to install
        
        installing package data to build/bdist.linux-x86_64/egg
        running install_data
        creating build
        creating build/bdist.linux-x86_64
        creating build/bdist.linux-x86_64/egg
        creating build/bdist.linux-x86_64/egg/etc
        copying autosuspend.conf -> build/bdist.linux-x86_64/egg/etc
        copying autosuspend-logging.conf -> build/bdist.linux-x86_64/egg/etc
        creating build/bdist.linux-x86_64/egg/lib
        creating build/bdist.linux-x86_64/egg/lib/systemd
        creating build/bdist.linux-x86_64/egg/lib/systemd/system
        copying autosuspend.service -> build/bdist.linux-x86_64/egg/lib/systemd/system
        creating build/bdist.linux-x86_64/egg/EGG-INFO
        installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
        running install_scripts
        running build_scripts
        creating build/scripts-3.4
        copying and adjusting autosuspend.py -> build/scripts-3.4
        changing mode of build/scripts-3.4/autosuspend.py from 644 to 755
        creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
        copying build/scripts-3.4/autosuspend.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
        changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/autosuspend.py to 755
        copying autosuspend.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
        copying autosuspend.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
        copying autosuspend.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
        copying autosuspend.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
        copying autosuspend.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
        copying autosuspend.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
        creating dist
        creating 'dist/autosuspend-0.4_dev-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
        removing 'build/bdist.linux-x86_64/egg' (and everything under it)
        Processing autosuspend-0.4_dev-py3.4.egg
        creating /usr/local/lib/python3.4/dist-packages/autosuspend-0.4_dev-py3.4.egg
        Extracting autosuspend-0.4_dev-py3.4.egg to /usr/local/lib/python3.4/dist-packages
        Adding autosuspend 0.4-dev to easy-install.pth file
        Installing autosuspend.py script to /usr/local/bin
        
        Installed /usr/local/lib/python3.4/dist-packages/autosuspend-0.4_dev-py3.4.egg
        Processing dependencies for autosuspend==0.4-dev
        Searching for psutil
        Reading https://pypi.python.org/simple/psutil/
        Best match: psutil 4.1.0
        Downloading https://pypi.python.org/packages/source/p/psutil/psutil-4.1.0.tar.gz#md5=017e1023484ebf436d3514ebeaf2e7e9
        Processing psutil-4.1.0.tar.gz
        Writing /tmp/easy_install-63637atg/psutil-4.1.0/setup.cfg
        Running psutil-4.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-63637atg/psutil-4.1.0/egg-dist-tmp-sderqmhx
        warning: no previously-included files matching '*' found under directory 'docs/_build'
        unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
        error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

   I installed this via aptitude, then install finishes well.

2. there is no /etc/autosuspend.conf file created during install

3. systemd

        root@linuxbox:/etc# systemd enable autosuspend.service
        Excess arguments.
        root@linuxbox:/etc# systemd start autosuspend.service
        Excess arguments.
        
        root@linuxbox:/etc# uname -a
        Linux linuxbox 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u4 (2016-02-29) x86_64 GNU/Linux

So just like you to know....

**Comment by languitar** [comment] 2016-03-25 10:11
The error you first observe during `python3 setup.py install` is caused by the upstream dependency psutil. setuptools tries to download and compile the native parts of that dependency but it can't find a compiler installed on your system. There is probably a [distribution package for psutil](https://packages.debian.org/search?keywords=python3-psutil). If you install this first, you can completely skip the manual compilation.

The other errors are caused by the fact that you are installing to `/usr/local/` as the prefix. This is the default for setuptools and also a good idea if you are installing system-wide software which is not handled by your distribution's package manager. Therefore, the config file should be installed as `/usr/local/etc/autosuspend.conf`. Additionally, the systemd unit file will be installed in a non-default location, which systemd doesn't search. You need to manually copy `autosuspend.service` to a location which is searched by systemd (usually `/etc/systemd/system/`) and inside that file change the paths to match your installation directory in `/usr/local`. Before using systemd at all, you could also first try out the script manually by launching it in the terminal via `python3 /usr/local/bin/autosuspend.py -c /usr/local/etc/autosuspend.conf`. This is probably also a good idea to find suitable settings.

**Comment by languitar** [comment] 2016-03-30 07:59
I don't think there is much that I can actually solve inn this code. So I am closing the issue.

**Closed** 2016-05-06 10:10 UTC
